app:
  port: ":4000"

db:
  host: "172.17.0.2"
  port: "5432"
  user: "postgres"
  password: "mysecretpassword"
  name: "postgres"
  maxIdleConns: 30
  maxOpenConns: 10
  maxConnLifetime: 10

jwt:
  secret: "secret"
  tokenLifeTimeHour: 24
